"""First migration_54

Revision ID: 4ab691f0cb61
Revises: 17984eb67f5b
Create Date: 2023-02-17 09:01:45.567429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab691f0cb61'
down_revision = '17984eb67f5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'last_name')
    op.drop_column('orders', 'first_name')
    # ### end Alembic commands ###
